# Generated by Django 4.2.3 on 2023-08-10 18:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("match", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="match",
            name="location",
        ),
    ]
