# Generated by Django 4.2.3 on 2023-12-19 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0007_alter_match_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='minute_of_event',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
