# Generated by Django 4.2.3 on 2023-12-20 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0009_remove_match_minute_of_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='minute_of_event',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
