# Generated by Django 4.2.3 on 2023-12-20 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0010_match_minute_of_event'),
    ]

    operations = [
        migrations.RenameField(
            model_name='match',
            old_name='minute_of_event',
            new_name='minute_of_goal',
        ),
    ]
