# Generated by Django 4.2.3 on 2023-12-20 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0012_remove_match_minute_of_goal_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matchplayerstats',
            name='minute_of_goal',
        ),
        migrations.AddField(
            model_name='matchplayerstats',
            name='minutes_of_goal',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
