# Generated by Django 4.2.3 on 2023-12-28 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0014_match_stage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='stage',
            field=models.CharField(choices=[('Final', 'Final'), ('Semi-finals', 'Semi-finals'), ('Quarter-finals', 'Quarter-finals'), ('Play-offs', 'Play-offs'), ('Round 3', 'Round 3'), ('Round 2', 'Round 2'), ('Round 1', 'Round 1')], default='Round 1', max_length=20),
        ),
    ]
