# Generated by Django 4.2.3 on 2023-07-23 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("team", "0008_player_clean_sheets"),
        ("auth_app", "0008_alter_captainuser_profile_picture"),
    ]

    operations = [
        migrations.AddField(
            model_name="captainuser",
            name="captain_team",
            field=models.OneToOneField(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="team.team",
            ),
        ),
    ]
