# Generated by Django 4.2.3 on 2023-07-23 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0009_captainuser_captain_team'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='captainuser',
            name='captain_team',
        ),
    ]
