# Generated by Django 4.2.3 on 2023-08-08 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0011_captainuser_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='captainuser',
            name='added_players',
            field=models.BooleanField(default=False),
        ),
    ]
