version: '3.4'

services:
  web:
    image: borisangelovv/smg_cl_final
    build: .
    command: gunicorn --bind=0.0.0.0:8000 smgCLFinalProject.wsgi:application
    ports:
      - "8000:8000"
    env_file:
      - ./envs/.env
    volumes:
      - /tmp/smg_cl_final/static:/app/static
  postgres:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: smg-user
      POSTGRES_DB: smg_cl_final_db
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./postgresql:/var/lib/postgresql/data
  nginx:
    image: nginx
    ports:
      - "81:80"
      - "443:443"
    volumes:
      - /tmp/smg_cl_final/static:/home/app/web/staticfiles
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/logs:/var/log/nginx
      - ./certbot/www:/var/www/certbot/:ro
      - ./certbot/conf/:/etc/nginx/ssl/:ro
    links:
      - web