# Generated by Django 4.2.3 on 2023-08-12 10:15

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("content", models.TextField()),
                ("image", models.ImageField(upload_to="article_images")),
                ("date", models.DateTimeField(auto_now_add=True)),
                ("author", models.CharField(max_length=100)),
            ],
        ),
    ]
