# Generated by Django 4.2.3 on 2023-07-23 11:56

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0004_alter_team_paralelki'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='paralelki',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=1), default=list, size=3),
        ),
    ]
