# Generated by Django 4.2.3 on 2023-07-23 12:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("team", "0005_alter_team_paralelki"),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="is_captain",
            field=models.BooleanField(default=False),
        ),
    ]
