# Generated by Django 4.2.3 on 2023-07-29 14:45

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0009_alter_team_paralelki'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='paralelki',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=1), blank=True, default=list, null=True, size=6),
        ),
    ]
