# Generated by Django 4.2.3 on 2023-08-11 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0012_team_goal_difference'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='mvps',
            field=models.IntegerField(default=0),
        ),
    ]
