# Generated by Django 4.2.3 on 2023-08-11 13:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("team", "0014_alter_player_options"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="team",
            name="last_three_games",
        ),
    ]
