# Generated by Django 4.2.3 on 2023-10-13 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0015_remove_team_last_three_games'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='allowed_teams',
            field=models.ManyToManyField(related_name='allowed_teams_vs', to='team.team'),
        ),
    ]
